name: CI

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./

      # Make sure the latest changes from the pull request are used.
      - name: Install
        run: sudo ln -svf $PWD/bin/mkosi /usr/bin/mkosi
        working-directory: ./

      - name: Build tools tree
        run: |
          tee mkosi.local.conf <<EOF
          [Build]
          ToolsTreeDistribution=arch
          EOF

          mkosi -f box -- true

      - name: Run unit tests
        run: mkosi box -- python3 -m pytest -sv

      - name: Test execution from current working directory (sudo call)
        run: sudo python3 -m mkosi -h
